name: Release ffmpeg-2204-sdk to candidate

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "2204" ]
    paths: 
      - "ffmpeg-2204-sdk/**"
  workflow_dispatch:
    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  get-architectures:
    name: 🖥 Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: 🖥 Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main
        with:
          snapcraft-project-root: "ffmpeg-2204-sdk"

  release-sdk-amd64:
    name: 🚢 Release to latest/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "2204 Branch"
    steps:
      - name: 🚢 Release to latest/candidate
        uses: jnsgruk/snapcrafters-ci/release-to-candidate@build-id-fix
        with:
          architecture: "amd64"
          channel: "candidate"
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          snapcraft-project-root: "ffmpeg-2204-sdk"
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}

  release-sdk-arm64:
    name: 🚢 Release to latest/candidate
    needs: release-sdk-amd64
    runs-on: ubuntu-latest
    environment: "2204 Branch"
    steps:
      - name: 🚢 Release to latest/candidate
        uses: jnsgruk/snapcrafters-ci/release-to-candidate@build-id-fix
        with:
          architecture: "arm64"
          channel: "candidate"
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          snapcraft-project-root: "ffmpeg-2204-sdk"
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}

  release-sdk-armhf:
    name: 🚢 Release to latest/candidate
    needs: release-sdk-arm64
    runs-on: ubuntu-latest
    environment: "2204 Branch"
    steps:
      - name: 🚢 Release to latest/candidate
        uses: jnsgruk/snapcrafters-ci/release-to-candidate@build-id-fix
        with:
          architecture: "armhf"
          channel: "candidate"
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          snapcraft-project-root: "ffmpeg-2204-sdk"
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}

  call-for-testing:
    name: 📣 Create call for testing
    needs: [release-sdk-armhf, get-architectures]
    environment: "2204 Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: 📣 Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
